#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform texture2D source_texture;
layout(set = 0, binding = 1, std430) buffer Result
{
    uint value;
} result_buffer;
layout(set = 1, binding = 0) uniform sampler source_sampler;

void main()
{
    vec4 color = texture(sampler2D(source_texture, source_sampler), vec2(0.5));
    result_buffer.value = packUnorm4x8(color);
}
