#version 450

#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform texture2D source_textures[];
layout(set = 1, binding = 0) uniform sampler source_sampler;
layout(set = 2, binding = 0, std430) buffer Result
{
    uint value;
} result_buffer;

layout(push_constant) uniform Parameters
{
    uint descriptor_index;
} parameters;

void main()
{
    vec4 color = texture(
        sampler2D(source_textures[parameters.descriptor_index],
                  source_sampler),
        vec2(0.5));
    result_buffer.value = packUnorm4x8(color);
}
